orm:
  backend: django_peeringdb
  database:
    engine: postgresql
    host: db
    name: luje
    password: <snip>
    user: luje
  migrate: true
  secret_key: ''
sync:
  api_key: <snip>
  only: []
  strip_tz: 1
  timeout: 0
  url: https://www.peeringdb.com/api
