services:
#  tunnel:
#    image: cloudflare/cloudflared:latest
#    restart: unless-stopped
#    command: tunnel --no-autoupdate run
#    environment:
#      TUNNEL_TOKEN: eyJhIjoiY2M0NzUxM2EzNjdjMzE4Yjg3MGE2MzIwNDk1NzdkYzUiLCJ0IjoiMzMxNmUyZTctNGY2YS00ZmQ4LWI5ODAtYzI2MGEwYTRiZTdlIiwicyI6Ik4yWmlOV1ZoTjJNdE5XWXpZUzAwT1dKa0xXRmtZall0TldGaU5EVTJNR1F3TW1aayJ9
  db:
    image: mariadb:lts
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: <snip>
      MYSQL_DATABASE: luje
      MYSQL_USER: luje
      MYSQL_PASSWORD: <snip>
    volumes:
      - ./db-data:/var/lib/mysql
  sync:
    image: git.luje.net/docker/website/luje:sync
    restart: unless-stopped
    entrypoint: /bin/sh -c 'while [ 1 ]; do sleep 1000; done'
    depends_on:
      - db
    volumes:
      - ./config.yaml:/root/.peeringdb/config.yaml
  web:
    image: git.luje.net/docker/website/luje:web
    restart: unless-stopped
    environment:
      DATABASE_SERVER: db
      DATABASE_USER: luje
      DATABASE_PASSWORD: <snip>
      DATABASE_NAME: luje
      PORTAL_HOSTNAME: www.luje.net
      PORTAL_OWNER_ASN: 212855
      PORTAL_EXPORT: AS212855:AS-LUJE
      PEERINGDB_CLIENTID: <snip>
      PEERINGDB_CLIENTSECRET: <snip>
    ports:
      - "2040:8080"
    depends_on:
      - db
  mailer:
    image: git.luje.net/docker/website/luje:mailer
    restart: unless-stopped
    entrypoint: /bin/sh -c 'while [ 1 ]; do sleep 1000; done'
    environment:
      DATABASE_SERVER: db
      DATABASE_USER: luje
      DATABASE_PASSWORD: <snip>
      DATABASE_NAME: luje
      MAIL_SERVER: mail-server
      MAIL_PORT: 25
      MAIL_USER: <snip>
      MAIL_PASSWORD: <snip>
      MAIL_FROM: hostmaster@luje.net
      MAIL_TLS: <snip>
    depends_on:
      - db
  peering:
    image: git.luje.net/docker/website/luje:peering
    restart: unless-stopped
    entrypoint: /bin/sh -c 'while [ 1 ]; do sleep 1000; done'
    environment:
      DATABASE_SERVER: db
      DATABASE_USER: luje
      DATABASE_PASSWORD: <snip>
      DATABASE_NAME: luje
      PORTAL_OWNER_ASN: 212855
      PORTAL_EXPORT: AS212855:AS-LUJE
      PORTAL_RIPE_PASSWORD: <snip>
      ROUTEFILTERS_LOCATION: /opt/routefilters
    volumes:
      - ./routefilters:/opt/routefilters
      - ./ssh:/root/.ssh
      - ./peeringconfig.json:/app/peeringconfig.json
    depends_on:
      - db
  ofelia:
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    command: daemon --config=/schedule.ini
    depends_on:
      - sync
      - mailer
      - peering
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./schedule.ini:/schedule.ini
        
networks: 
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-luje
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.4.0/24
        - subnet: fd4d:6169:6c63:4::/64
