services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: luje
      POSTGRES_DB: luje
      POSTGRES_PASSWORD: <snip>
    ports:
      - "15432:5432"
  sync:
    image: git.luje.net/docker/website/luje:sync
    restart: unless-stopped
    entrypoint: /bin/sh -c 'while [ 1 ]; do sleep 1000; done'
    depends_on:
      - db
    volumes:
      - ./config.yaml:/root/.peeringdb/config.yaml
  web:
    image: git.luje.net/docker/website/luje:web
    restart: unless-stopped
    volumes:
      - ./keys:/keys
    environment:
      DATABASE_SERVER: db
      DATABASE_USER: luje
      DATABASE_PASSWORD: <snip>
      DATABASE_NAME: luje
      PORTAL_HOSTNAME: www.luje.net
      PORTAL_OWNER_ASN: 212855
      PORTAL_EXPORT: AS212855:AS-LUJE
      PEERINGDB_CLIENTID: <snip>
      PEERINGDB_CLIENTSECRET: <snip>
    ports:
      - "2040:8080"
    depends_on:
      - db
  mailer:
    image: git.luje.net/docker/website/luje:mailer
    restart: unless-stopped
    entrypoint: /bin/sh -c 'while [ 1 ]; do sleep 1000; done'
    environment:
      DATABASE_SERVER: db
      DATABASE_USER: luje
      DATABASE_PASSWORD: <snip>
      DATABASE_NAME: luje
      MAIL_SERVER: <snip>
      MAIL_PORT: <snip>
      MAIL_USER: <snip>
      MAIL_PASSWORD: <snip>
      MAIL_FROM: <snip>
      MAIL_TLS: False
    depends_on:
      - db
  peering:
    image: git.luje.net/docker/website/luje:peering
    restart: unless-stopped
    entrypoint: /bin/sh -c 'while [ 1 ]; do sleep 1000; done'
    environment:
      DATABASE_SERVER: db
      DATABASE_USER: luje
      DATABASE_PASSWORD: <snip>
      DATABASE_NAME: luje
      PORTAL_OWNER_ASN: 212855
      PORTAL_EXPORT: AS212855:AS-LUJE
      PORTAL_RIPE_PASSWORD: <snip>
      ROUTEFILTERS_LOCATION: /opt/routefilters
    volumes:
      - ./routefilters:/opt/routefilters
      - ./ssh:/root/.ssh
      - ./peeringconfig.json:/app/peeringconfig.json
    depends_on:
      - db
  ofelia:
    image: mcuadros/ofelia:latest
    restart: unless-stopped
    command: daemon --config=/schedule.ini
    depends_on:
      - sync
      - mailer
      - peering
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./schedule.ini:/schedule.ini
        
networks: 
  default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-luje
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.4.0/24
        - subnet: fd4d:6169:6c63:4::/64
