/*
 * AutoPeer
 *
 * AutoPeering Negotiation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using LUJEWebsite.PeeringApi.Converters;

namespace LUJEWebsite.PeeringApi.Models
{ 
        /// <summary>
        /// Gets or Sets LocationType
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<LocationType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum LocationType
        {
            
            /// <summary>
            /// Enum PrivateEnum for private
            /// </summary>
            [EnumMember(Value = "private")]
            PrivateEnum = 1,
            
            /// <summary>
            /// Enum PublicEnum for public
            /// </summary>
            [EnumMember(Value = "public")]
            PublicEnum = 2
        }
}
