/*
 * AutoPeer
 *
 * AutoPeering Negotiation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using LUJEWebsite.PeeringApi.Converters;
using System.Text.Json.Serialization;

namespace LUJEWebsite.PeeringApi.Models
{ 
    /// <summary>
    /// location for session, contains an object with fields id &#x60;pdb:ix:$ID&#x60; and type PUBLIC or PRIVATE
    /// </summary>
    [DataContract]
    public class Location
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
		[JsonPropertyName("id")]
		public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=true)]
		[JsonPropertyName("type")]
		public LocationType Type { get; set; }
    }
}
