/*
 * AutoPeer
 *
 * AutoPeering Negotiation.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using LUJEWebsite.PeeringApi.Converters;
using System.Text.Json.Serialization;

namespace LUJEWebsite.PeeringApi.Models
{ 
    /// <summary>
    /// BGP Session
    /// </summary>
    [DataContract]
    public class Session
    {
        /// <summary>
        /// Gets or Sets LocalAsn
        /// </summary>
        [DataMember(Name="local_asn", EmitDefaultValue=true)]
		[JsonPropertyName("local_asn")]
		public int LocalAsn { get; set; }

        /// <summary>
        /// Gets or Sets LocalIp
        /// </summary>
        [DataMember(Name="local_ip", EmitDefaultValue=false)]
		[JsonPropertyName("local_ip")]
		public string LocalIp { get; set; }

        /// <summary>
        /// Gets or Sets PeerAsn
        /// </summary>
        [DataMember(Name="peer_asn", EmitDefaultValue=true)]
		[JsonPropertyName("peer_asn")]
		public int PeerAsn { get; set; }

        /// <summary>
        /// Gets or Sets PeerIp
        /// </summary>
        [DataMember(Name="peer_ip", EmitDefaultValue=false)]
		[JsonPropertyName("peer_ip")]
		public string PeerIp { get; set; }

        /// <summary>
        /// Gets or Sets PeerType
        /// </summary>
        [DataMember(Name="peer_type", EmitDefaultValue=false)]
		[JsonPropertyName("peer_type")]
		public string PeerType { get; set; }

        /// <summary>
        /// Gets or Sets Md5
        /// </summary>
        [DataMember(Name= "session_secret ", EmitDefaultValue=false)]
		[JsonPropertyName("session_secret")]
		public string SessionSecret { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name="location", EmitDefaultValue=false)]
		[JsonPropertyName("location")]
		public Location Location { get; set; }

        /// <summary>
        /// Add choices
        /// </summary>
        /// <value>Add choices</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
		[JsonPropertyName("status")]
		public string Status { get; set; }

        /// <summary>
        /// unique identifier (also serves as request id) Could separate into local_ and peer_?
        /// </summary>
        /// <value>unique identifier (also serves as request id) Could separate into local_ and peer_?</value>
        [DataMember(Name="session_id", EmitDefaultValue=false)]
		[JsonPropertyName("session_id")]
		public string SessionId { get; set; }

		/// <summary>
		/// unique identifier (also serves as request id) Could separate into local_ and peer_?
		/// </summary>
		/// <value>unique identifier (also serves as request id) Could separate into local_ and peer_?</value>
		[DataMember(Name = "request_id", EmitDefaultValue = false)]
		[JsonPropertyName("request_id")]
		public string RequestId { get; set; }
	}
}
